---
# tasks file for froxlor
- include: preseed.yml
- include: froxlor.repo.yml

- name: lamp
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
    - apache2
    - libapache2-mod-php5
    - mysql-server
    - phpmyadmin
    - php5-gd
    - php5-imap
    - php5-curl

- name: setup .my.conf
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: MTA and MDA
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
    - postfix
    - postfix-mysql
    - ssl-cert
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-mysql

- name: FTP
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
    - openbsd-inetd
    - proftpd-mod-mysql

- name: install froxlor
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
    - bind9
    - froxlor

- include: froxlor.config.yml tags=froxlor.config
- include: froxlor.http.yml tags=froxlor.http
- include: froxlor.ftp.yml tags=froxlor.ftp
- include: froxlor.dns.yml tags=froxlor.dns
- include: froxlor.imap_pop.yml tags=froxlor.imap_pop
- include: froxlor.smtp.yml tags=froxlor.smtp
