---
- name: restart bind
  service: >
    name=bind9
    state=restarted

- name: restart dovecot
  service: >
    name=dovecot
    state=restarted

- name: restart postfix
  service: >
    name=postix
    state=restarted

- name: newaliases
  command: newaliases

